version: '3'

#https://getakka.net/articles/remoting/deployment.html

services:
  # lighthouse:
    # image: petabridge/lighthouse:v0.9.2
    # ports:
      # - '9110:9110'
      # - '4053:4053'
    # environment:
      # ACTORSYSTEM: "mycluster"
      # CLUSTER_IP: lighthouse
      # CLUSTER_PORT: 4053
      # CLUSTER_SEEDS: "akka.tcp://mycluster@lighthouse:4053"

  app2-ping:
    build:
      context: .
      dockerfile: ConsoleApp2.Ping/Dockerfile
    environment:
      # CLUSTER_SEEDS: "akka.tcp://mycluster@lighthouse:4053"
      # CLUSTER_IP: ping
      # CLUSTER_PORT: 0
    # depends_on:
      # - "lighthouse"

  app2-pong:
    build:
      context: .
      dockerfile: ConsoleApp2.Pong/Dockerfile
    environment:
      # CLUSTER_SEEDS: "akka.tcp://mycluster@lighthouse:4053"
      # CLUSTER_IP: pong
      # CLUSTER_PORT: 0
    # depends_on:
      # - "lighthouse"